#!/usr/bin/env python3
"""Generate the file tables of the sample state root's README from ``FILES``.

Every module's ``store.py`` declares the files it writes (``FILES``, see
``services/storage/files.py``). This script renders those declarations as
the table between the ``<!-- generated: files -->`` and
``<!-- /generated: files -->`` markers in
``tests/fixtures/quirq-state/README.md`` and, with ``--check``, exits 1 when
the file is stale (``tests/test_modules.py`` runs that check).

    venv/bin/python scripts/write_layout_docs.py            # rewrite the block
    venv/bin/python scripts/write_layout_docs.py --check    # exit 1 when stale
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

README = REPO / "tests" / "fixtures" / "quirq-state" / "README.md"
START = "<!-- generated: files -->"
END = "<!-- /generated: files -->"


def render() -> str:
    from services import modules as registry
    from services.storage.files import LOSE

    rows = sorted(registry.files(), key=lambda pair: (pair[1].tier, pair[1].pattern))
    lines = [START,
             "",
             "Generated by `scripts/write_layout_docs.py` from every module's `FILES`; do not edit by hand.",
             "",
             "| File | Module | Role | Kept | Delete it and you lose |",
             "|---|---|---|---|---|"]
    for module, spec in rows:
        where = spec.pattern if spec.tier == "local" else f"<project>/.xo/{spec.pattern}"
        kept = spec.rotate or spec.keep or ("append-only" if spec.log else "")
        note = f" ({spec.note})" if spec.note else ""
        lines.append(f"| `{where}` | {module} | {spec.role} | {kept} | {LOSE[spec.role]}{note} |")
    lines += ["", END]
    return "\n".join(lines)


def current() -> str:
    text = README.read_text(encoding="utf-8")
    if START not in text or END not in text:
        return ""
    return text[text.index(START): text.index(END) + len(END)]


def write() -> bool:
    text = README.read_text(encoding="utf-8")
    block = render()
    if START in text and END in text:
        new = text[: text.index(START)] + block + text[text.index(END) + len(END):]
    else:
        new = text.rstrip("\n") + "\n\n## The files every module declares\n\n" + block + "\n"
    if new != text:
        README.write_text(new, encoding="utf-8")
        return True
    return False


def main(argv: list[str]) -> int:
    if "--check" in argv:
        if current() != render():
            print(f"{README} is stale: run venv/bin/python scripts/write_layout_docs.py", file=sys.stderr)
            return 1
        print("layout docs current")
        return 0
    print("updated" if write() else "unchanged", README)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
