#!/usr/bin/env python3
"""Generate the HTTP reference from the mounted routers.

Renders ``.agents/skills/xo-projects/references/routes.md``: one section per
module (and the kernel), one row per route with its method, path and the
first line of the handler's docstring. With ``--check`` it exits 1 when the
file is stale (``tests/test_modules.py`` runs that check), so the reference
an agent reads can never drift from what the server mounts.

    venv/bin/python scripts/write_route_docs.py            # rewrite
    venv/bin/python scripts/write_route_docs.py --check    # exit 1 when stale
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

TARGET = REPO / ".agents" / "skills" / "xo-projects" / "references" / "routes.md"


def _rows(router) -> list[tuple[str, str, str]]:
    """The routes a router contributes once mounted, from the OpenAPI document
    of a throwaway app (this FastAPI resolves an included router lazily, so
    the router's own ``routes`` list is not the flat set)."""
    from fastapi import FastAPI

    app = FastAPI()
    app.include_router(router)
    rows = []
    for path, operations in app.openapi().get("paths", {}).items():
        for method, operation in operations.items():
            if method.upper() in {"HEAD", "OPTIONS"}:
                continue
            description = (operation.get("description") or "").strip()
            summary = description.splitlines()[0] if description else ""
            rows.append((method.upper(), path, summary))
    return sorted(set(rows), key=lambda r: (r[1], r[0]))


def _agent_own_paths() -> set[str]:
    """The active agent's own routes (adapters/<name>/routes.py) depend on
    AGENT_NAME, so the reference leaves them out to stay the same on every
    machine; scripts/check_route_parity.py lists them per agent."""
    try:
        from services.cowork_agent.adapters.loader import try_load_capability
        mod = try_load_capability("routes")
        router = getattr(mod, "router", None) if mod else None
        return {r.path for r in getattr(router, "routes", [])} if router is not None else set()
    except Exception:  # noqa: BLE001 - no active agent resolvable: nothing to exclude
        return set()


def render() -> str:
    from services import modules as registry
    from routers.kernel import router as kernel_router
    from routers.space import router as space_router

    own = _agent_own_paths()

    out = ["# HTTP routes",
           "",
           "Generated by `scripts/write_route_docs.py` from the mounted routers; do not edit by hand.",
           "Every route below belongs to a module (`modules/<name>/routes.py`), mounted behind that",
           "module's `api` switch: a module turned off in Setup answers 404 `module_disabled`. Streams",
           "(`/api/<module>/stream/<name>`) are server-sent events. The kernel's own routes are listed last;",
           "the active agent's own routes (`adapters/<name>/routes.py`) are not listed, they depend on AGENT_NAME.",
           ""]
    for module, router in registry.routers():
        out.append(f"## {module.title} (`modules/{module.name}`)")
        out.append("")
        if module.description:
            out.append(module.description)
            out.append("")
        out.append("| Method | Path | What it does |")
        out.append("|---|---|---|")
        for method, path, summary in _rows(router):
            if module.name == "agent" and path in own:
                continue
            out.append(f"| {method} | `{path}` | {summary} |")
        for _m, name, _fn in registry.streams():
            if _m.name == module.name:
                out.append(f"| GET | `/api/{module.name}/stream/{name}` | server-sent events |")
        out.append("")
    out.append("## The kernel")
    out.append("")
    out.append("| Method | Path | What it does |")
    out.append("|---|---|---|")
    for method, path, summary in _rows(kernel_router) + _rows(space_router):
        out.append(f"| {method} | `{path}` | {summary} |")
    out.append("")
    return "\n".join(out)


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != text:
            print(f"{TARGET} is stale: run venv/bin/python scripts/write_route_docs.py", file=sys.stderr)
            return 1
        print("route docs current")
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    changed = not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != text
    TARGET.write_text(text, encoding="utf-8")
    print("updated" if changed else "unchanged", TARGET)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
